// Generated by https://quicktype.io

export interface ResponseVendedores {
  data:    Vendedores[];
  ok:      boolean;
  message: string;
}

export interface Vendedores {
  codigo:          string;
  cedula:          string;
  descripcion:     string;
  id_ruta:         IDRuta;
  id_clase:        IDClase;
  id_supervisor:   string;
  clase_desc_vend: ClaseDescVend;
}

export enum ClaseDescVend {
  Administrador = "ADMINISTRADOR",
  Callcenter = "CALLCENTER",
  Compras = "COMPRAS",
  Empty = "",
  Inactivo = "INACTIVO",
  Mayoristas = "MAYORISTAS",
  VendExterno = "VEND_EXTERNO",
  Vendedores = "VENDEDORES",
}

export enum IDClase {
  Admo = "ADMO",
  Call = "CALL",
  Comp = "COMP",
  Empty = "",
  Exte = "EXTE",
  May = "MAY",
  Vend = "VEND",
  Xxxx = "XXXX",
}

export enum IDRuta {
  Empty = "",
  The00101 = "00101",
}

// Generated by https://quicktype.io

export interface ResponseVendedor {
  data:    Vendedor;
  ok:      boolean;
  message: string;
}

export interface Vendedor {
  codigo:          string;
  cedula:          string;
  descripcion:     string;
  id_ruta:         string;
  id_clase:        string;
  id_supervisor:   string;
  clase_desc_vend: string;
}
